### ISSUE TITLE
Unknown object type "asyncfunction"

### ISSUE THREAD

**Issue by walshe** [sindresorhus/serialize-error#75]
I love serize error but all of a sudden today (in the cloud) I started getting the following error in my app.  Since `serialize-error` seems to be the only lib using `object-hash`,  I decided to remove serialize-error.. and everything was ok again.. any idea why it happens ?

```
/var/www/node_modules/object-hash/index.js:218
          throw new Error('Unknown object type "' + objType + '"');
                ^

Error: Unknown object type "asyncfunction"
    at Object._object (/var/www/node_modules/object-hash/index.js:218:17)
    at Object._function (/var/www/node_modules/object-hash/index.js:319:14)
    at Object.dispatch (/var/www/node_modules/object-hash/index.js:185:30)
    at /var/www/node_modules/object-hash/index.js:246:18
    at Array.forEach (<anonymous>)
    at Object._object (/var/www/node_modules/object-hash/index.js:242:21)
    at Object._function (/var/www/node_modules/object-hash/index.js:319:14)
    at Object.dispatch (/var/www/node_modules/object-hash/index.js:185:30)
    at /var/www/node_modules/object-hash/index.js:246:18
    at Array.forEach (<anonymous>)
```

**Comment by fregante** [comment]
`serialize-error` does not use `object-hash`

https://github.com/sindresorhus/serialize-error/blob/6f6102fc0690922a7aa14537b52908e983c27b81/package.json#L39

**Comment by walshe** [comment]
i seen this in my yarn.lock so figured it did ?:

@fregante 
```
serialised-error@^1.1.3:
  version "1.1.3"
  resolved "https://registry.yarnpkg.com/serialised-error/-/serialised-error-1.1.3.tgz#8a4c466b29c26ff11016eaf1b5fa2b87ca4cd8b5"
  integrity sha512-vybp3GItaR1ZtO2nxZZo8eOo7fnVaNtP3XE2vJKgzkKR2bagCkdJ1EpYYhEMd3qu/80DwQk9KjsNSxE3fXWq0g==
  dependencies:
    object-hash "^1.1.2"
    stack-trace "0.0.9"
    uuid "^3.0.0"
```

**Comment by walshe** [comment]
apologies.. wrong lib :(
